### ISSUE TITLE
Latest version is not published correctly

### ISSUE THREAD

**Issue by mdvanes** [yw662/deno_markdown_tree#1]
Hi, thank you for your library!

It seems that the latest version published on deno.land is not the same as the last version on Github, although release 1.1.0 and the commit both have 31 March as the date.

Maybe this is on purpose, either way I am looking forward to using your updates to HTMLHelper. Thanks in advance!

**Comment by yw662** [comment]
Yeah it is intended since it is not finished and fully tested for now. However I am not currently working on it recently, so feel free to do anything to it.

**Comment by mdvanes** [comment]
Thanks for letting me know. Since it's intentional, and I would need to figure out the requirements first, I'll consider this closed.

**Comment by yw662** [comment]
Glad to know you are interested with this project. Maybe you will find another project of mine, tsx_static also useful :-).
